config/routes.rb
Rails.application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  scope module: 'client_side' do
    root to: 'home#index'
    resources :brands, only: [:index, :show]

    resources :subdivisions, only: [] do
      collection do
        get ':id/choice', to: 'subdivisions#choice'
      end
    end
    resources :product_groups, only: [:show], param: :slug do
      resources :product_categories, only: [:show], param: :slug do
      end
    end
    resources :products, only: [:show]
    resources :pages, only: [:show], param: :slug
    resources :news, only: [:index, :show]
    resources :client_feedbacks, only: [:create]

    # compare controller
    get 'compare', to: 'compare#index'
    post 'compare/add', to: 'compare#add'
    post 'compare/remove', to: 'compare#remove'

    # basket controller
    get 'basket', to: 'basket#index'
    post 'basket/add', to: 'basket#add'

    # orders controller
    resources :orders, only: [:create]

    get 'search', to: 'search#search'
  end
end

app/controllers/client_side/base_controller.rb
class ClientSide::BaseController < ApplicationController
  before_action :get_regions
  before_action :get_menu_elements
  before_action :get_top_menu_elements
  before_action :get_quantity_products
  before_action :get_bottom_menu_elements
  before_action :new_client_feedback
  before_action :get_basket_products
  before_action :get_banner_under_header

  helper_method :current_subdivision

  # before_action :set_location

  # def set_location
  #   if session[:location].nil?
  #     session[:location] = FreeGeoIp.geocode request.remote_ip
  #   else

  #   end
  # end

  def get_regions
    @regions = Region.includes(cities: :subdivision).all
  end

  def get_menu_elements
    @menu_elements = MenuElement.where(subdivision_id: current_subdivision&.id)
  end

  def get_top_menu_elements
    @top_menu_elements = NavigationElement.where(subdivision_id: current_subdivision&.id)
      .top
      .order(:order)
  end

  def get_bottom_menu_elements
    @bottom_menu_elements = NavigationElement.where(subdivision_id: current_subdivision&.id)
      .bottom
      .order(:order)
  end

  def get_quantity_products
    @quantity_products = Product.count
  end

  def new_client_feedback
    @client_feedback = ClientFeedback.new(subdivision_id: current_subdivision&.id)
    @letter_subjects = LetterSubject.where(subdivision_id: current_subdivision&.id)
    @client = Client.new
  end

  def get_basket_products
    @basket_products = Product.where(id: session[:basket])
  end

  def get_banner_under_header
    @banner_under_header = Banner.under_header.last
  end

  private
    def current_subdivision
      if session[:subdivision_id].nil?
        Subdivision.find_by main: 1
      else
        Subdivision.find session[:subdivision_id]
      end
    end
end

app/controllers/client_side/basket_controller.rb
module ClientSide
  class BasketController < BaseController
    def index
      @products = Product.where(id: session[:basket])
      @order = Order.new
      @client = Client.new
    end

    def add
      if session[:basket].nil?
        session[:basket] = []
      end
      session[:basket] << params[:id]
    end
  end
end

app/controllers/client_side/brands_controller.rb
class ClientSide::BrandsController < ClientSide::BaseController
  def index
    @brands = Brand.all.order(:name)
  end

  def show
    @brand = Brand.find(params[:id])
  end
end

app/controllers/client_side/client_feedbacks_controller.rb
module ClientSide
  class ClientFeedbacksController < BaseController
    def create
      @client_feedback = ClientFeedback.new(client_feedback_params)
      @client_feedback.subdivision = current_subdivision

      params[:client][:phone].gsub!(/\D/, '')
      @client = Client.find_by(phone: client_params[:phone])
      @client ||= Client.new(client_params)
      @client.save
      @client_feedback.client = @client

      respond_to do |format|
        if @client_feedback.save and @client.save
          format.json { render json: @client_feedback, status: :created }
        else
          format.json { render status: :unprocessable_entity}
        end
      end
    end

    private
      def client_params
        params.require(:client).permit(:first_name, :phone, :email)
      end

      def client_feedback_params
        params.require(:client_feedback).permit(:letter_subject_id, :content)
      end
  end
end

app/controllers/client_side/compare_controller.rb
module ClientSide
  class CompareController < BaseController
    def index
      @product_groups = ProductGroup.includes(product_categories: :products)
                                    .where('products.id' => session[:compare_products])
    end

    def add
      if session[:compare_products].nil?
        session[:compare_products] = []
      end
      if params[:id].is_a? Integer or params[:id].is_a? String
        session[:compare_products] << params[:id]
      end

      respond_to do |format|
        if session[:compare_products].include?(params[:id])
          format.json{
            render json: {
              count: session[:compare_products].count
            },
            status: 200
          }
        else
          format.json{ render json: {}, status: 400 }
        end
      end
    end

    def remove
      session[:compare_products].delete(params[:id])
      respond_to do |format|
        unless session[:compare_products].include?(params[:id])
          format.json{
            render json: {
              count: session[:compare_products].count
            },
            status: 200
          }
        else
          format.json{ render json: {}, status: 400 }
        end
      end
    end
  end
end

app/controllers/client_side/home_controller.rb
class ClientSide::HomeController < ClientSide::BaseController
  def index
    @popular_product_groups = PopularProductGroup.by_subdivision current_subdivision
    @brands = Brand.where(show_on_home: true)
    
    @slides = []
    
    @slides << Banner.main_slide.to_a
    @slides << Banner.minor_slide.to_a.shuffle
    @slides.flatten!
  end
end

app/controllers/client_side/news_controller.rb
module ClientSide
  class NewsController < BaseController
    def index 
      @news = News.active
      @last_news = News.all.active.order(:updated_at).last(3)
    end
    def show
      @news = News.active.find(params[:id])
      @last_news = News.active.order(:updated_at).last(3)
    end
  end
end

app/controllers/client_side/orders_controller.rb
module ClientSide
  class OrdersController < BaseController
    def create
      params[:order][:client][:phone].gsub!(/\D/, '')
      @client = Client.find_by(phone: client_params[:phone])
      @client ||= Client.new(client_params)
      @client.save

      @products = Product.where(id: session[:basket])

      @order = Order.new
      @order.client = @client
      @order.subdivision = current_subdivision
      respond_to do |format|
        if @order.save
          format.json { render json: @order, status: :created }
        else

        end
      end
    end

    private
      def client_params
        params.require(:order)
              .require(:client)
              .permit(:first_name, :phone, :email)
      end
  end
end

app/controllers/client_side/pages_controller.rb
module ClientSide
  class PagesController < BaseController
    def show
      @page = Page.find_by(slug: params[:slug])
    end
  end
end

app/controllers/client_side/product_categories_controller.rb
class ClientSide::ProductCategoriesController < ClientSide::BaseController
  def show
    @product_category = ProductCategory.find_by(slug: params[:slug])

    @products = @product_category.products
                                 .page(params[:page])
                                 .per(params[:per])

    @product_group = @product_category.product_group
    sort_params = params[:sort_by]

    @products.order!(sort_params[0] => sort_params[1]) unless sort_params.nil?

    @last_news = News.active.order(:updated_at).last(3)
  end
end

app/controllers/client_side/product_groups_controller.rb
class ClientSide::ProductGroupsController < ClientSide::BaseController
  def show
    @product_group = ProductGroup.find_by(slug: params[:slug])
    if @product_group.nil?
      raise ActiveRecord::RecordNotFound, "Товарная группа не найдена."
    end
  end
end

app/controllers/client_side/products_controller.rb
class ClientSide::ProductsController < ClientSide::BaseController
  def show
    @product = Product.includes(brand: :country).find(params[:id])
    @product_category = @product.product_category
    @product_group = @product_category.product_group
    @products_history = get_products_history
    add_to_history_product product: @product
  end

  private
    def add_to_history_product product:
      if session[:product_history].nil?
        session[:product_history] = []
      end
      session[:product_history] << product.id unless session[:product_history].include?(product.id)
      if session[:product_history].length > 3
        session[:product_history] = session[:product_history].last(3)
      end
    end

    def get_products_history
      result = []
      unless session[:product_history].nil?
        session[:product_history].each do |id|
          result << Product.find(id)
        end
      end
      result.reverse
    end
end

app/controllers/client_side/search_controller.rb
module ClientSide
  class SearchController < BaseController
    def search
      if params[:q].nil?
        @articles = []
      else
        debugger
        @articles = Product.search params[:q]
      end
    end
  end
end

app/controllers/client_side/subdivisions_controller.rb
class ClientSide::SubdivisionsController < ClientSide::BaseController
  def choice
    session[:subdivision_id] = params[:id]
    redirect_to :back
  end
end

app/helpers/client_side/basket_helper.rb
module ClientSide::BasketHelper
end

app/helpers/client_side/brands_helper.rb
module ClientSide
  module BrandsHelper
    def list_letters list
      list.map{|x| x[0].upcase}.uniq
    end
  end
end

app/helpers/client_side/compare_helper.rb
module ClientSide::CompareHelper
end

app/helpers/client_side/home_helper.rb
module ClientSide
  module HomeHelper
  end
end

app/helpers/client_side/orders_helper.rb
module ClientSide::OrdersHelper
end

app/helpers/client_side/pages_helper.rb
module ClientSide
  module PagesHelper

  end
end

app/views/client_side/compare/index.html.erb
<section class="content">
  <div class="uk-container uk-container-center compare">
    <div class="compare__title-grouup">
      <h2 class="compare__title">Сравнение товаров:</h2>
      <% @product_groups.each do |product_group| %>
        <%= link_to product_group.name, '#', class: 'compare__group-link' %>
      <% end %>
    </div>
    <div class="compare__control-group">
      <div class="uk-button btn btn--blue-inverse is-active compare__control-button" onclick="$('.compare__control-button').removeClass('is-active');$(this).addClass('is-active');">Все характеристики</div>
      <div class="uk-button btn btn--blue-inverse btn--nobl compare__control-button" onclick="$('.compare__control-button').removeClass('is-active');$(this).addClass('is-active');">Только отличающиеся</div>
    </div>
    <% @product_groups.each do |product_group| %>
    <h3 class="compare__group-title"><%= product_group.name %></h3>
    <div class="uk-overflow-container">
      <table class="compare__table">
        <tr>
          <td class="compare__td-char"></td>
          <% product_group.product_categories.each do |product_category| %>
            <% product_category.products.each do |product| %>
              <td>
                <%= image_tag product.image.url(:thumb), class: 'compare__item-image' %>
              </td>
            <% end %>
          <% end %>
        </tr>
        <tr>
          <td class="compare__td-char">Модель</td>
            <% product_group.product_categories.each do |product_category| %>
              <% product_category.products.each do |product| %>
                <td>
                  <%= link_to product.name,
                              product_path(product),
                              class: 'link--blue-red link--td-inverse' %>
                  <%= link_to compare_remove_path,
                              data: {id: product.id},
                              class: 'link--red' do %>
                    <i class="uk-icon-close"></i>
                  <% end %>
                </td>
            <% end %>
          <% end %>
        </tr>
        <tr>
          <td class="compare__td-char">Артикул</td>
          <% product_group.product_categories.each do |product_category| %>
            <% product_category.products.each do |product| %>
            <td>
              <%= product.article %>
            </td>
            <% end %>
          <% end %>
        </tr>
        <tr>
          <td class="compare__td-char">Цена</td>
          <% product_group.product_categories.each do |product_category| %>
            <% product_category.products.each do |product| %>
              <td>
                <div>5 132 <span class="rub compare__rub"></span></div>
                <a class="uk-button btn btn--red btn--rounded btn--mw135 search__to-cart" data-uk-modal href="#modal-added-to-cart"><i class="uk-icon-shopping-cart"></i>В корзину</a>
              </td>
            <% end %>
          <% end %>
        </tr>
        <!-- <tr class="compare__tr-similar">
          <td class="compare__td-char">Бренд инсталляции</td>
          <td>Cersanit</td>
          <td>Cersanit</td>
          <td>Cersanit</td>
          <td>Cersanit</td>
        </tr>
        <tr class="compare__tr-similar">
          <td class="compare__td-char">Бренд унитаза</td>
          <td>Cersanit</td>
          <td>Cersanit</td>
          <td>Cersanit</td>
          <td>Cersanit</td>
        </tr> -->
      </table>
    </div>
    <% end %>
  </div>
</section>