config/routes.rb
Rails.application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  scope module: 'client_side' do
    root to: 'home#index'
    resources :brands, only: [:index, :show]

    resources :subdivisions, only: [] do
      collection do
        get ':id/choice', to: 'subdivisions#choice'
      end
    end
    resources :product_groups, only: [:show], param: :slug do
      resources :product_categories, only: [:show], param: :slug do
      end
    end
    resources :products, only: [:show]
    resources :pages, only: [:show], param: :slug
    resources :news, only: [:index, :show]
    resources :client_feedbacks, only: [:create]

    # compare controller
    get 'compare', to: 'compare#index'
    post 'compare/add', to: 'compare#add'
    post 'compare/remove', to: 'compare#remove'

    # basket controller
    get 'basket', to: 'basket#index'
    post 'basket/add', to: 'basket#add'

    # orders controller
    resources :orders, only: [:create]

    get 'search', to: 'search#search'
  end
end

app/views/admin/catalog/_sidebar.html.erb
<ul class='sidebar'>
  <%= render 'sidebar_tree', collection: @product_groups %>
<ul>

app/views/admin/catalog/_sidebar_tree.html.erb
<% collection.each do |group| %>
  <li class="group <%= group.root? ? 'root' : '' %>">
    <% if group.is_childless? %>
      <span>
        <%= group.name %>
      </span>
      <%= link_to fa_icon('edit'),
                  edit_admin_product_group_path(group),
                  title: 'Редактировать' %>
      <%= link_to fa_icon('eye'),
                  admin_product_group_path(group),
                  title: 'Просмотреть' %>
    <% else %>
      <span>
        <%= group.name %>
      </span>
      <%= link_to fa_icon('edit'),
                  edit_admin_product_group_path(group),
                  title: 'Редактировать' %>
      <%= link_to fa_icon('eye'),
                  admin_product_group_path(group),
                  title: 'Просмотреть' %>
      <ul>
        <%= render 'sidebar_tree', collection: group.children %>
      </ul>
    <% end %>
    <ul>
      <% if group.has_categories? %>
        <% group.product_categories.each do |category| %>
          <li class="category">
            <%= link_to products_admin_product_category_path(category), remote: true do %>
              <%= category.name %>
            <% end %>
            <%= link_to fa_icon('edit'),
                        edit_admin_product_category_path(category),
                        title: 'Редактировать' %>
            <%= link_to fa_icon('eye'),
                        admin_product_category_path(category),
                        title: 'Просмотреть' %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </li>
<% end %>