config/routes.rb
Rails.application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  scope module: 'client_side' do
    root to: 'home#index'
    resources :brands, only: [:index, :show]

    resources :subdivisions, only: [] do
      collection do
        get ':id/choice', to: 'subdivisions#choice'
      end
    end
    resources :product_groups, only: [:show], param: :slug do
      resources :product_categories, only: [:show], param: :slug do
      end
    end
    resources :products, only: [:show]
    resources :pages, only: [:show], param: :slug
    resources :news, only: [:index, :show]
    resources :client_feedbacks, only: [:create]

    # compare controller
    get 'compare', to: 'compare#index'
    post 'compare/add', to: 'compare#add'
    post 'compare/remove', to: 'compare#remove'

    # basket controller
    get 'basket', to: 'basket#index'
    post 'basket/add', to: 'basket#add'

    # orders controller
    resources :orders, only: [:create]

    get 'search', to: 'search#search'
  end
end

app/models/product_category.rb
# == Schema Information
#
# Table name: product_categories
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  article          :string(255)
#  meta_tags        :text(65535)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  product_group_id :integer
#  subdivision_id   :integer
#  slug             :string(255)
#  image            :string(255)
#  old_id           :integer
#
# Indexes
#
#  index_product_categories_on_article           (article)
#  index_product_categories_on_product_group_id  (product_group_id)
#  index_product_categories_on_subdivision_id    (subdivision_id)
#

class ProductCategory < ActiveRecord::Base
  include SlugHelper

  validates :name, presence: true
  validates :article, presence: true, uniqueness: true

  belongs_to :product_group
  belongs_to :subdivision

  has_many :products

  has_many :product_categories_characteristics
  has_many :product_characteristics, through: :product_categories_characteristics

  mount_uploader :image, ImageUploader

  before_save :add_slug

  def self.available user, current_subdivision
    if user.subdivisions.include? current_subdivision
      where(subdivision_id: current_subdivision)
    end
  end

  def url
    "#{product_group.url}/product_categories/#{slug}"
  end

  private
    def add_slug
      self.slug = slug_generate self.name
    end
end

app/controllers/client_side/base_controller.rb
class ClientSide::BaseController < ApplicationController
  before_action :get_regions
  before_action :get_menu_elements
  before_action :get_top_menu_elements
  before_action :get_quantity_products
  before_action :get_bottom_menu_elements
  before_action :new_client_feedback
  before_action :get_basket_products
  before_action :get_banner_under_header

  helper_method :current_subdivision

  # before_action :set_location

  # def set_location
  #   if session[:location].nil?
  #     session[:location] = FreeGeoIp.geocode request.remote_ip
  #   else

  #   end
  # end

  def get_regions
    @regions = Region.includes(cities: :subdivision).all
  end

  def get_menu_elements
    @menu_elements = MenuElement.where(subdivision_id: current_subdivision&.id)
  end

  def get_top_menu_elements
    @top_menu_elements = NavigationElement.where(subdivision_id: current_subdivision&.id)
      .top
      .order(:order)
  end

  def get_bottom_menu_elements
    @bottom_menu_elements = NavigationElement.where(subdivision_id: current_subdivision&.id)
      .bottom
      .order(:order)
  end

  def get_quantity_products
    @quantity_products = Product.count
  end

  def new_client_feedback
    @client_feedback = ClientFeedback.new(subdivision_id: current_subdivision&.id)
    @letter_subjects = LetterSubject.where(subdivision_id: current_subdivision&.id)
    @client = Client.new
  end

  def get_basket_products
    @basket_products = Product.where(id: session[:basket])
  end

  def get_banner_under_header
    @banner_under_header = Banner.under_header.last
  end

  private
    def current_subdivision
      if session[:subdivision_id].nil?
        Subdivision.find_by main: 1
      else
        Subdivision.find session[:subdivision_id]
      end
    end
end

app/controllers/client_side/basket_controller.rb
module ClientSide
  class BasketController < BaseController
    def index
      @products = Product.where(id: session[:basket])
      @order = Order.new
      @client = Client.new
    end

    def add
      if session[:basket].nil?
        session[:basket] = []
      end
      session[:basket] << params[:id]
    end
  end
end

app/controllers/client_side/brands_controller.rb
class ClientSide::BrandsController < ClientSide::BaseController
  def index
    @brands = Brand.all.order(:name)
  end

  def show
    @brand = Brand.find(params[:id])
  end
end

app/controllers/client_side/client_feedbacks_controller.rb
module ClientSide
  class ClientFeedbacksController < BaseController
    def create
      @client_feedback = ClientFeedback.new(client_feedback_params)
      @client_feedback.subdivision = current_subdivision

      params[:client][:phone].gsub!(/\D/, '')
      @client = Client.find_by(phone: client_params[:phone])
      @client ||= Client.new(client_params)
      @client.save
      @client_feedback.client = @client

      respond_to do |format|
        if @client_feedback.save and @client.save
          format.json { render json: @client_feedback, status: :created }
        else
          format.json { render status: :unprocessable_entity}
        end
      end
    end

    private
      def client_params
        params.require(:client).permit(:first_name, :phone, :email)
      end

      def client_feedback_params
        params.require(:client_feedback).permit(:letter_subject_id, :content)
      end
  end
end

app/controllers/client_side/compare_controller.rb
module ClientSide
  class CompareController < BaseController
    def index
      @product_groups = ProductGroup.includes(product_categories: :products)
                                    .where('products.id' => session[:compare_products])
    end

    def add
      if session[:compare_products].nil?
        session[:compare_products] = []
      end
      if params[:id].is_a? Integer or params[:id].is_a? String
        session[:compare_products] << params[:id]
      end

      respond_to do |format|
        if session[:compare_products].include?(params[:id])
          format.json{
            render json: {
              count: session[:compare_products].count
            },
            status: 200
          }
        else
          format.json{ render json: {}, status: 400 }
        end
      end
    end

    def remove
      session[:compare_products].delete(params[:id])
      respond_to do |format|
        unless session[:compare_products].include?(params[:id])
          format.json{
            render json: {
              count: session[:compare_products].count
            },
            status: 200
          }
        else
          format.json{ render json: {}, status: 400 }
        end
      end
    end
  end
end

app/controllers/client_side/home_controller.rb
class ClientSide::HomeController < ClientSide::BaseController
  def index
    @popular_product_groups = PopularProductGroup.by_subdivision current_subdivision
    @brands = Brand.where(show_on_home: true)
    
    @slides = []
    
    @slides << Banner.main_slide.to_a
    @slides << Banner.minor_slide.to_a.shuffle
    @slides.flatten!
  end
end

app/controllers/client_side/news_controller.rb
module ClientSide
  class NewsController < BaseController
    def index 
      @news = News.active
      @last_news = News.all.active.order(:updated_at).last(3)
    end
    def show
      @news = News.active.find(params[:id])
      @last_news = News.active.order(:updated_at).last(3)
    end
  end
end

app/controllers/client_side/orders_controller.rb
module ClientSide
  class OrdersController < BaseController
    def create
      params[:order][:client][:phone].gsub!(/\D/, '')
      @client = Client.find_by(phone: client_params[:phone])
      @client ||= Client.new(client_params)
      @client.save

      @products = Product.where(id: session[:basket])

      @order = Order.new
      @order.client = @client
      @order.subdivision = current_subdivision
      respond_to do |format|
        if @order.save
          format.json { render json: @order, status: :created }
        else

        end
      end
    end

    private
      def client_params
        params.require(:order)
              .require(:client)
              .permit(:first_name, :phone, :email)
      end
  end
end

app/controllers/client_side/pages_controller.rb
module ClientSide
  class PagesController < BaseController
    def show
      @page = Page.find_by(slug: params[:slug])
    end
  end
end

app/controllers/client_side/product_categories_controller.rb
class ClientSide::ProductCategoriesController < ClientSide::BaseController
  def show
    @product_category = ProductCategory.find_by(slug: params[:slug])

    @products = @product_category.products
                                 .page(params[:page])
                                 .per(params[:per])

    @product_group = @product_category.product_group
    sort_params = params[:sort_by]

    @products.order!(sort_params[0] => sort_params[1]) unless sort_params.nil?

    @last_news = News.active.order(:updated_at).last(3)
  end
end

app/controllers/client_side/product_groups_controller.rb
class ClientSide::ProductGroupsController < ClientSide::BaseController
  def show
    @product_group = ProductGroup.find_by(slug: params[:slug])
    if @product_group.nil?
      raise ActiveRecord::RecordNotFound, "Товарная группа не найдена."
    end
  end
end

app/controllers/client_side/products_controller.rb
class ClientSide::ProductsController < ClientSide::BaseController
  def show
    @product = Product.includes(brand: :country).find(params[:id])
    @product_category = @product.product_category
    @product_group = @product_category.product_group
    @products_history = get_products_history
    add_to_history_product product: @product
  end

  private
    def add_to_history_product product:
      if session[:product_history].nil?
        session[:product_history] = []
      end
      session[:product_history] << product.id unless session[:product_history].include?(product.id)
      if session[:product_history].length > 3
        session[:product_history] = session[:product_history].last(3)
      end
    end

    def get_products_history
      result = []
      unless session[:product_history].nil?
        session[:product_history].each do |id|
          result << Product.find(id)
        end
      end
      result.reverse
    end
end

app/controllers/client_side/search_controller.rb
module ClientSide
  class SearchController < BaseController
    def search
      if params[:q].nil?
        @articles = []
      else
        debugger
        @articles = Product.search params[:q]
      end
    end
  end
end

app/controllers/client_side/subdivisions_controller.rb
class ClientSide::SubdivisionsController < ClientSide::BaseController
  def choice
    session[:subdivision_id] = params[:id]
    redirect_to :back
  end
end

app/helpers/client_side/basket_helper.rb
module ClientSide::BasketHelper
end

app/helpers/client_side/brands_helper.rb
module ClientSide
  module BrandsHelper
    def list_letters list
      list.map{|x| x[0].upcase}.uniq
    end
  end
end

app/helpers/client_side/compare_helper.rb
module ClientSide::CompareHelper
end

app/helpers/client_side/home_helper.rb
module ClientSide
  module HomeHelper
  end
end

app/helpers/client_side/orders_helper.rb
module ClientSide::OrdersHelper
end

app/views/client_side/product_categories/_breadcrumbs.html.erb
<div class="breadcrumbs no-select">
  <%= link_to 'Главная', root_path, class: 'breadcrumbs__item breadcrumbs__item--first breadcrumbs__item--1' %>
  <%= link_to @product_group.name, product_group_path(@product_group.slug), class: 'breadcrumbs__item breadcrumbs__item--2' %>
  <span class='breadcrumbs__item breadcrumbs__item--last breadcrumbs__item--3'><%= @product_category.name %></span>
</div>

app/views/client_side/product_categories/_product.html.erb
<div class="uk-width-1-1 uk-width-medium-1-3 uk-width-large-1-4 cg__good">
  <div href="/catalog_good.html" class="cg__good-cont">
    <div class="cg__good-art">
      <% unless product.brand.nil? || product.brand.country.nil? %>
        <%= image_tag product.brand.country.flag.url if product.brand.country.flag.file.exists? %>
      <% end %>
      Артикул: <%= product.article %>
      <i class="uk-icon-list-ul cg__good-tocompare <%= 'is-active' if session[:compare_products]&.include?(product.id.to_s) %>"></i>
    </div>
    <%= link_to product.name,
                product_path(product),
                class: 'cg__good-name' %>

    <%= link_to product_path(product) do %>
      <% if product.image.file.exists? %>
        <%= image_tag product.image.url(:thumb) %>
      <% else %>
        <%= image_tag product.image.default_url(:thumb) %>
      <% end %>
    <% end %>

    <div class="cg__good-about">
      Сигнализатор загазованности СКЗ-Кристалл DN15(СН4) c двумя порогами срабатывания Энергосистемы Сигнализатор загазованности Турбулентность Дон СКЗ-Кристалл DN15(СН4) c двумя порогами срабатывания. Контролирует уровень природного газа в помещении.
    </div>
    <div class="cg__price">
      <%= product.price(current_subdivision).price_kopecks unless product.price(current_subdivision).nil? %> <span class="rub"></span>
      <!-- <span class="cg__old-price">8999 <span class="rub"></span></span> -->
    </div>
    <a class="uk-button btn btn--light-red btn--rounded btn--mw135 cg__good-cart" href="/cart.html">
      <i class="uk-icon-shopping-cart"></i>Добавлено
    </a>
  </div>
  <input type="hidden" name="id" value="<%= product.id %>">
</div>

app/views/client_side/product_categories/_sort.html.erb
<div class="cg__sort">
  <%= link_to 'По цене',
        params.merge(sort_by: ['price_kopecks', 'asc']),
        class: 'uk-button btn btn--light-blue btn--rounded btn--sorting btn--sorting-down' %>

  <div class="uk-button btn btn--light-blue btn--rounded is-active btn--sorting btn--sorting-up">
    По популярности
  </div>
  <div class="uk-button btn btn--red btn--rounded">
    Только акции
  </div>
  <span class="cg__sort-count">
    Всего товаров - <%= @product_category.products.count %>
  </span>
  
  <div class="uk-button btn btn--rounded btn--sq btn--light-blue uk-hidden-small js-catalog-to-th-list">
    <i class="uk-icon-th-list"></i>
  </div>
  <div class="uk-button btn btn--rounded btn--sq btn--light-blue uk-hidden-small js-catalog-to-th is-active">
    <i class="uk-icon-th"></i>
  </div>&nbsp;&nbsp;
  <%= active_link_to '30',
        params.merge(per: nil),
        class: 'uk-button btn btn--rounded btn--sq btn--light-blue',
        class_active: 'is-active',
        active: :exact %>
  <%= active_link_to '60',
        params.merge(per: 60),
        class: 'uk-button btn btn--rounded btn--sq btn--light-blue',
        class_active: 'is-active',
        active: :exact %>
  <%= active_link_to '90',
        params.merge(per: 90),
        class: 'uk-button btn btn--rounded btn--sq btn--light-blue',
        class_active: 'is-active',
        active: :exact %>&nbsp;&nbsp;
  <div class="uk-button btn btn--rounded btn--sq btn--light-blue">→</div>
</div>

app/views/client_side/product_categories/show.html.erb
<section class="content">
  <div class="uk-container uk-container-center cg">
    <div class="uk-grid">
      <div class="uk-width-1-1 uk-width-medium-5-7 uk-width-large-4-5 uk-push-2-7">
        <%= render partial: 'breadcrumbs' %>
        <%= render partial: 'sort' %>
        <div class="uk-grid uk-grid-xsmall cg__grid">
          <% @products.each do |product| %>
            <%= render partial: 'product', locals: {product: product} %>
          <% end %>
        </div>
        <%= paginate @products %>
      </div>
      <div class="uk-width-1-1 uk-width-medium-2-7 uk-width-large-1-5 uk-pull-5-7">
        <div class="cf uk-hidden-small">
          <!--
            Всплывающая плашка - Показать при изменении фильтра
            Убрать uk-hidden
           -->
          <div class="cf__search-result uk-hidden" style="top: 230px;">
            Найдено 87 <a href="#">Показать</a>
          </div>
          <div class="cf__title no-select">Стоимость, Р</div>
          <div class="cf__range-group">
            <div class="cf__input-group">
              <input type="text" value="2500"> -
              <input type="text" value="2900">
            </div>
            <div class="cf__range-slider" data-min="10" data-max="500" data-start="100" data-end="400"></div>
          </div>
          <div class="cf__title no-select">Размеры, мм</div>
          <div class="cf__range-group">
            <div class="cf__input-group">
              <input type="text" value="2500"> -
              <input type="text" value="2900">
            </div>
            <div class="cf__range-slider"></div>
          </div>
          <div class="cf__title cf__title--toggled is-open no-select">
            Бренд инсталляции
            <i class="uk-icon-info-circle cf__info" data-uk-tooltip="{pos:'bottom-left'}" title="Накопительный - вода нагреется в специальном баке в процессе работы нагревательного элемента.
                Проточный - нагревание воды происходит практически мгновенно после ее прохождения через теплообменник.
                Проточно-накопительный - комбинированный тип нагрева воды.
                Бойлер - горячая вода циркулирует в контуре большой ёмкости."></i>
          </div>
          <div class="cf__group uk-form">
            <label class="uk-margin-small-top"><input type="checkbox" name="ch-1"> Alcaplast</label>
            <label class="uk-margin-small-top"><input type="checkbox" name="ch-2"> Adidas</label>
            <label class="uk-margin-small-top"><input type="checkbox" name="ch-2"> Nike</label>
          </div>
          <div class="cf__title cf__title--toggled no-select">
            Заголовок
            <i class="uk-icon-info-circle cf__info" data-uk-tooltip="{pos:'bottom-left'}" title="Накопительный - вода нагреется"></i>
          </div>
          <div class="cf__group uk-form">
            <label class="uk-margin-small-top"><input type="checkbox" name="ch-1"> Только в наличии</label>
            <label class="uk-margin-small-top"><input type="checkbox" name="ch-2"> Только в акциях</label>
          </div>
          <div class="cf__controls">
            <a href="#" class="uk-button btn btn--blue btn--rounded cf__control-show">Показать</a>
            <a href="#" class="link link--light-gray link--dotted text--medium">Сбросить</a>
          </div>
        </div>
        <%= render 'shared/last_news' %>
      </div>
    </div>
  </div>
</section>