config/routes.rb
Rails.application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  scope module: 'client_side' do
    root to: 'home#index'
    resources :brands, only: [:index, :show]

    resources :subdivisions, only: [] do
      collection do
        get ':id/choice', to: 'subdivisions#choice'
      end
    end
    resources :product_groups, only: [:show], param: :slug do
      resources :product_categories, only: [:show], param: :slug do
      end
    end
    resources :products, only: [:show]
    resources :pages, only: [:show], param: :slug
    resources :news, only: [:index, :show]
    resources :client_feedbacks, only: [:create]

    # compare controller
    get 'compare', to: 'compare#index'
    post 'compare/add', to: 'compare#add'
    post 'compare/remove', to: 'compare#remove'

    # basket controller
    get 'basket', to: 'basket#index'
    post 'basket/add', to: 'basket#add'

    # orders controller
    resources :orders, only: [:create]

    get 'search', to: 'search#search'
  end
end

app/views/shared/_catalog_top_menu.html.erb
<div class="cm-catalog-nav">
  <div class="cm-slider">
    <ul class="cm-slider__ul js-cm-slider" id="catalog-top-slider">
      <% @menu_elements.roots.order(:order).each do |root_element| %>
        <li class="cm-slider__item">
          <%= image_tag root_element.image.url, class: 'cm-slider__item-img' %>
          <div class="cm-slider__item-name">
            <%= root_element.name %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="cm-slider__sub-menu uk-container-full uk-container-center">

    <% @menu_elements.roots.order(:order).each do |root_element| %>
      <div class="uk-grid uk-grid-small cm-slider__group">
        <div class="uk-width-1-1 uk-width-medium-1-2 uk-width-large-1-4">
          <% root_element.children.where(column: 1).order(:order).each do |children| %>
            <a href="<%= children.link %>" class="cm-slider__sub-menu-item <%= 'cm-slider__sub-menu-item--parent' if children.is_title %>">
              <%= children.name %>
            </a>
          <% end %>
        </div>
        <div class="uk-width-1-1 uk-width-medium-1-2 uk-width-large-1-4">
          <% root_element.children.where(column: 2).order(:order).each do |children| %>
            <a href="<%= children.link %>" class="cm-slider__sub-menu-item <%= 'cm-slider__sub-menu-item--parent' if children.is_title %>">
              <%= children.name %>
            </a>
          <% end %>
        </div>
        <div class="uk-width-1-1 uk-width-medium-1-2 uk-width-large-1-4">
          <% root_element.children.where(column: 3).order(:order).each do |children| %>
            <a href="<%= children.link %>" class="cm-slider__sub-menu-item <%= 'cm-slider__sub-menu-item--parent' if children.is_title %>">
              <%= children.name %>
            </a>
          <% end %>
        </div>
        <div class="uk-width-1-1 uk-width-medium-1-2 uk-width-large-1-4">
          <% root_element.children.where(column: 4).order(:order).each do |children| %>
            <a href="<%= children.link %>" class="cm-slider__sub-menu-item <%= 'cm-slider__sub-menu-item--parent' if children.is_title %>">
              <%= children.name %>
            </a>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_fixed_cart.html.erb
<div class="fixed">
  <%= link_to compare_path,
              class: 'fixed__item fixed__item--compare' do %>
    <div class="fixed__title">
      Сравнение <span><%= session[:compare_products]&.count || 0 %> </span>
    </div>
  <% end %>
  <div class="fixed__item fixed__item--cart">
    <a href="/cart.html" class="fixed__title">
      <i class="uk-icon-shopping-cart"></i> Корзина <span>
        <%= @basket_products.count %>
      </span>
    </a>
    <div class="fixed__content">
      <a href="#" class="fixed__c-remove-all">Убрать все</a>
      <div class="fixed__c-title">Ваш заказ</div>
      <div class="fixed__c-content">
        <% @basket_products.each do |product| %>
        <div class="fixed__c-item">
          <div class="uk-grid uk-grid-xsmall">
            <div class="uk-width-5-10 fixed__c-name-cont">
              <%= link_to product.name, product_path(product), class: 'fixed__c-name' %>
            </div>
            <div class="uk-width-2-10">
              <input type="number" value="1" class="fixed__c-input">
            </div>
            <div class="uk-width-3-10">
              <div class="fixed__c-price">1162 <span class="rub"></span> <i class="uk-icon-times-circle fixed__c-remove"></i></div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <div class="fixed__c-itog">
        Всего на сумму:
        <div class="fixed__c-price">1162 <span class="rub"></span></div>
        <a href="/cart.html" class="uk-button btn--rounded btn--white btn--small btn--xrounded fixed__c-order">Оформить</a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="uk-container uk-container-center">
    <div class="uk-grid">
      <div class="uk-width-1-1 uk-width-medium-3-10 footer__grid-cell">
        <div class="footer__logo-cont">
          <img class="footer__logo" src="/images/logo.png" alt="">
        </div>
        <div class="footer__links-cont">
          <% @bottom_menu_elements.each do |element| %>
            <%= link_to element.name,
                        element.link,
                        class: 'footer__link link--gray link--td-inverse' %>
          <% end %>
          <a href="#" class="footer__link link--gray link--td-inverse">Письмо директору</a>
          <a href="#" class="footer__link link--gray link--td-inverse">Корзина</a>
        </div>
      </div>
      <div class="uk-width-1-1 uk-width-medium-2-10 footer__grid-cell">
        <img class="footer__stat" src="/images/temp/stat.png" alt="">
      </div>
      <div class="uk-width-1-1 uk-width-medium-5-10 footer__grid-cell">
        <div class="footer__text">
          Указанные на сайте цены не являются публичной офертой (ст.435 ГК РФ).<br>
          Используемые на сайте изображения товаров могут включать дополнительное оборудование и компоненты, не входящие в стандартную комплектацию товара.<br>
          © 2016 ESMAG — интернет-магазин сантехники в Екатеринбургe<br>
          Все цены указаны в рублях (PУБ.)<br>
          +7 (343) 389 98 98<br>
        </div>
        <a href="#" class="footer__email">info@esmag.ru</a>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <div class="uk-container-full uk-container-center">
    <div class="uk-grid">
      <div class="uk-width-1-1 uk-width-medium-2-10 uk-text-center-small">
        <a href="/"><img src="/images/logo.png" alt="Esmag" class="header__logo"></a>
      </div>
      <div class="uk-width-1-1 uk-width-medium-6-10 header__nav-cont" id="header-nav-cont">

        <ul class="header__nav">
          <% @top_menu_elements.each do |element| %>
            <li class="header__nav-item">
              <%= link_to element.name, element.link, class: 'header__nav-link' %>
            </li>
          <% end %>
          <li class="header__nav-item"><a href="#modal-contacts" data-uk-modal class="header__nav-link">Контакты</a></li>
          <li class="header__nav-item"><a href="#modal-message" data-uk-modal class="header__nav-link">Письмо директору</a></li>
        </ul>
        <div class="header__search">
          <%= form_for search_path, url: {action: 'search', controller: 'search'}, method: :get do |f| %>
            <%= text_field_tag :q, params[:q] %>
            <%= submit_tag "Go", name: nil %>
          <% end %>

        </div>
      </div>
      <div class="uk-width-1-1 uk-width-medium-2-10 uk-text-right uk-text-center-small">
        <div class="header__city">
          <a href="#modal-city" data-uk-modal="" class="header__city-link">
            <%= current_subdivision.city.name if current_subdivision %>
          </a>
        </div>
        <div class="header__phone">
          <%= current_subdivision&.phones %>
        </div>
      </div>
      <div class="uk-width-1-10 uk-visible-small uk-text-center header__nav-cell">
        <span class="header__navbar-toggle uk-visible-small js-navbar-toggle"></span>
      </div>
    </div>
  </div>

</header>

app/views/shared/_last_news.html.erb
<% unless @last_news.empty? %>
  <div class="last-news">
    <div class="last-news__title">
      Новости
    </div>
    <% @last_news.each do |item| %>
      <div class="last-news__item">
        <div class="last-news__item-date"><%= item.updated_at.to_formatted_s(:long) %></div>
        <%= link_to item.title, news_path(item), class: 'last-news__item-name' %>
        <div class="last-news__item-anons"><%= item.preview %></div>
      </div>
    <% end %>
    <div class="last-news__more-cont">
      <%= link_to "Все новости", news_index_path, class: 'uk-button btn btn--blue btn--rounded' %>
    </div>
  </div>
<% end %>

app/views/shared/_modal_added_to_cart.html.erb
<div id="modal-added-to-cart" class="uk-modal modal modal-added-to-cart modal--yellow">
    <div class="uk-modal-dialog">

        <a class="uk-modal-close uk-close--red uk-close modal__close modal__close--nomargin"></a>
        <h2>Добавлено в корзину</h2>
        <div class="modal__logo uk-text-center">
            <img src="/images/logo.png" alt="">
        </div>
        <div class="uk-grid matc__info">
            <div class="uk-width-1-1 uk-width-medium-1-3">
                <img src="/images/temp/good-big-1.jpg" alt="">
            </div>
            <div class="uk-width-1-1 uk-width-medium-2-3 matc__info-text">
                <p>В корзину добавлен товар</p>
                <p>Инсталляция Leon 5 в 1 + унитаз Delfi Cersanit</p>
                <div class="matc__controls">
                    <a href="/cart.html" class="uk-button btn btn--blue btn--rounded btn--mw135 matc__to-cart">Оформить заказ</a>
                    <a href="#" class="uk-modal-close matc__continue">Продолжить покупки</a>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_modal_city.html.erb
<div id="modal-city" class="uk-modal modal modal-city modal--yellow">
  <div class="uk-modal-dialog">
    <a class="uk-modal-close uk-close--red uk-close modal__close modal__close--nomargin"></a>
    <h2>Выберите ваш город</h2>
    <div class="modal__logo uk-text-center">
      <img src="/images/logo.png" alt="">
    </div>
    <div class="modal__text">
      <% @regions.each do |region| %>
        <% cities = region.cities.select{|city| city.subdivision != nil} %>
        <% unless cities.empty? %>
          <div class="modal__city-group">
            <div class="modal__city-name">
              <%= region.name %>
            </div>
            <div class="uk-grid modal__city-grid">
              
              <% cities.each do |city| %>
                <div class="uk-width-1-1 uk-width-medium-1-3">
                  <a href="/subdivisions/<%= city.subdivision.id %>/choice" class="modal__city-link">
                    <%= city.name %>
                  </a>
                </div>
              <% end %>
            </div>
            <p>
              <a href="#" class="modal__city-deliv">Прочесть условия доставки по региону</a>
            </p>
          </div>
          <hr>
        <% end %>
      <% end %>
    </div>
    <div class="modal__footer uk-text-center">
      <div class="uk-button btn btn--blue btn--rounded uk-modal-close">Закрыть окно</div>
    </div>
  </div>
</div>

app/views/shared/_modal_message.html.erb
<div id="modal-message" class="uk-modal modal modal-message">
  <div class="uk-modal-dialog">
    <a class="uk-modal-close uk-close modal__close modal__close--nomargin"></a>
    <h2>Письмо директору</h2>
    <%= form_for @client_feedback, html: {class: 'form'} do |f| %>
      <div class="form__group">
        <%= f.select :letter_subject_id do %>
          <option disabled>Выберите тему</option>
          <% @letter_subjects.each do |l| %>
            <%= content_tag(:option, l.name, value: l.id) %>
          <% end %>
        <% end %>
      </div>
      
      <div class="form__group">
        <div class="uk-form-icon uk-form-icon-flip uk-form-icon--right">
          <i class="uk-icon-user"></i>
          <%= fields_for @client do |c| %>
            <%= c.text_field :first_name %>
          <% end %>
        </div>
      </div>
      <div class="form__group">
        <div class="uk-form-icon uk-form-icon-flip uk-form-icon--right">
          <i class="uk-icon-phone"></i>
          <%= fields_for @client do |c| %>
            <%= c.text_field :phone, class: 'input-mask--phone' %>
          <% end %>
          <!-- <div class="form__help-block">Текс в случае неверного заполнения</div> -->
        </div>
      </div>
      <div class="form__group">
        <div class="uk-form-icon uk-form-icon-flip uk-form-icon--right">
          <i class="uk-icon-envelope"></i>
          <%= fields_for @client do |c| %>
            <%= c.text_field :email %>
          <% end %>
        </div>
      </div>
      <div class="form__group">
        <%= f.text_area :content, rows: 7%>
      </div>
      <div class="form__submit-cont uk-text-center">
        <div class="spinner">
          <div class="bounce1"></div>
          <div class="bounce2"></div>
          <div class="bounce3"></div>
        </div>
        <input type="submit" class="uk-button btn btn--blue btn--rounded" value="Отправить">
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_modal_ok.html.erb
<div id="modal-ok" class="uk-modal modal modal modal-ok">
  <div class="uk-modal-dialog">
    <a class="uk-modal-close uk-close modal__close modal__close--nomargin"></a>
    <h2>Успешно отправлено</h2>
    <div class="modal__text">
      <p>Спасибо, ваша заявка отправлена.</p>
      <p>Наши менеджеры свяжутся с вами в ближайшее время.</p>
    </div>
    <div class="modal__footer uk-text-center">
      <div class="uk-button btn btn--blue btn--rounded uk-modal-close">Все понятно</div>
    </div>
  </div>
</div>

app/views/shared/_scripts.html.erb
<script src="/components/jquery/jquery.min.js"></script>
<script src="/components/uikit-2.26.4/js/uikit.min.js"></script>
<script src="/components/uikit-2.26.4/js/components/tooltip.min.js"></script>
<script src="/components/uikit-2.26.4/js/components/lightbox.min.js"></script>
<script src="/components/owl-carousel/owl.carousel.min.js"></script>
<script src="/components/mixitup/jquery.mixitup.js"></script>
<script src="/components/jquery-custom-scrollbar-0.5.5/jquery.custom-scrollbar.min.js"></script>
<script src="/components/dataTable/jquery.dataTables.min.js"></script>
<script src="/components/jquery.maskedinput.min.js"></script>
<script src="/components/responsive-table/responsive-tables.js"></script>
<script src="/components/nouislider/nouislider.min.js"></script>

app/views/shared/_stylesheets.html.erb
<link href='https://fonts.googleapis.com/css?family=Ubuntu:400,300,400italic,500,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="/components/uikit-2.26.4/css/uikit.min.css">
<link rel="stylesheet" href="/components/uikit-2.26.4/css/components/form-advanced.css">
<link rel="stylesheet" href="/components/uikit-2.26.4/css/components/tooltip.css">
<link rel="stylesheet" href="/components/owl-carousel/owl.carousel.css">
<link rel="stylesheet" href="/components/jquery-custom-scrollbar-0.5.5/jquery.custom-scrollbar.css">
<link rel="stylesheet" href="/components/responsive-table/responsive-tables.css">
<link rel="stylesheet" href="/components/nouislider/nouislider.min.css">

app/views/shared/_top_adver.html.erb
<div class="top-adver">
  <div class="uk-container uk-container-center uk-text-center">
    <p>
      <b>Получить скидку 2%</b> за самовывоз
    </p>
  </div>
</div>